version: "3.7"
services:
  grocy:
    image: lscr.io/linuxserver/grocy:v3.3.2-ls175
    container_name: grocy
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - ${APP_PORT}:80
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.grocy.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.grocy.entrypoints: websecure
      traefik.http.routers.grocy.service: grocy
      traefik.http.routers.grocy.tls.certresolver: myresolver
      traefik.http.services.grocy.loadbalancer.server.port: 80
