version: '3.4'
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ports:
      - 9999:9999
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
    volumes:
      - /root/runtipi/app-data/stash:/root/.stash
      - /root/runtipi/app-data/stash/data:/data
      - /root/runtipi/app-data/stash/metadata:/metadata
      - /root/runtipi/app-data/stash/cache:/cache
      - /root/runtipi/app-data/stash/generated:/generated
