version: '3'

services:
  homeassistant-1:
    image: ghcr.io/home-assistant/home-assistant:2024.6.3
    container_name: homeassistant-1
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/config:/config