version: "3.7"
services:
  kapowarr:
    image: mrcas/kapowarr:v1.0.0-beta-1
    container_name: kapowarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/kapowarr-db:/app/db
      - ${ROOT_FOLDER_HOST}/media/downloads/kapowarr:/app/temp_downloads
      - ${ROOT_FOLDER_HOST}/media:/media
    ports:
      - ${APP_PORT}:5656
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.kapowarr.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.kapowarr.entrypoints: websecure
      traefik.http.routers.kapowarr.service: kapowarr
      traefik.http.routers.kapowarr.tls.certresolver: myresolver
      traefik.http.services.kapowarr.loadbalancer.server.port: 5656
