version: "3.3"
services:
  appflowy_client:
    image: appflowyio/appflowy_client:main
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - ${APP_DATA_DIR}/data:/home/appflowy
    environment:
      - DISPLAY=${DISPLAY}
    restart: unless-stopped
    networks:
    - tipi_main_network
