version: "3.7"
services:
  vikunja-db:
    container_name: vikunja-db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${VIKUNJA_DB_PASSWORD}
      POSTGRES_USER: tipi
      POSTGRES_DB: vikunja
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tipi_main_network

  vikunja-api:
    image: vikunja/api:0.21.0
    hostname: vikunja-api
    environment:
      VIKUNJA_DATABASE_HOST: vikunja-db
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_DB_PASSWORD}
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: tipi
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_SECRET}
      VIKUNJA_SERVICE_FRONTENDURL: ${APP_PROTOCOL:-http}://${APP_DOMAIN}/
    ports:
      - 3456:3456
    volumes:
      - ${APP_DATA_DIR}/data/files:/app/vikunja/files
    depends_on:
      vikunja-db:
        condition: service_healthy
    restart: unless-stopped
    container_name: vikunja-api
    networks:
      tipi_main_network:
        ipv4_address: 10.21.21.75

  vikunja:
    image: vikunja/frontend:0.21.0
    ports:
      - ${APP_PORT}:80
    environment:
      VIKUNJA_API_URL: http://10.21.21.75:3456/api/v1
    restart: unless-stopped
    container_name: vikunja
    networks:
      - tipi_main_network
