version: "3"

services:
  romm:
    image: zurdi15/romm:1.6.2
    container_name: romm
    environment:
      - ROMM_DB_DRIVER="mariadb" # This variable can be set as: mariadb | sqlite. If it is not defined, sqlite will be the database by default
      - DB_HOST=romm-db # Only if ROMM_DB_DRIVER='mariadb'
      - DB_PORT=3306 # Only if ROMM_DB_DRIVER='mariadb'
      - DB_USER=tipi # Only if ROMM_DB_DRIVER='mariadb'
      - DB_NAME=romm # Only if ROMM_DB_DRIVER='mariadb'. Can be optionally changed, and should match the MYSQL_DATABASE value in the mariadb container.
      - DB_PASSWD=${ROMM_MYSQL_PASSWORD} # Only if ROMM_DB_DRIVER='mariadb'
      - CLIENT_ID="${ROMM_IGDB_CLIENT_ID}"
      - CLIENT_SECRET="${ROMM_IGDB_CLIENT_SECRET}"
      - STEAMGRIDDB_API_KEY="${ROMM_STEAMGRIDDB_API_KEY}"
    restart: unless-stopped
    volumes:
      - ${ROOT_FOLDER_HOST}/media/data/roms:/romm/library
      - ${APP_DATA_DIR}/data/romm-resources:/romm/resources
      - ${APP_DATA_DIR}/data/config.yml:/romm/config.yml
    ports:
      - ${APP_PORT}:80
    depends_on:
      - romm-db
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.romm.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.romm.entrypoints: websecure
      traefik.http.routers.romm.service: romm
      traefik.http.routers.romm.tls.certresolver: myresolver
      traefik.http.services.romm.loadbalancer.server.port: 80

  romm-db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: romm-db
    environment:
      - MYSQL_ROOT_PASSWORD=${ROMM_MYSQL_PASSWORD}
      - MYSQL_DATABASE=romm
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${ROMM_MYSQL_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mysql/config:/config
    restart: "unless-stopped"
    networks:
      - tipi_main_network