version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-tipi
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${APP_DATA_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     networks:
      - tipi_main_network