
services:

  proxitok:
    container_name: proxitok
    image: ghcr.io/pablouser1/proxitok:master
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    environment:
      - "LATTE_CACHE=/cache"
      - "API_CACHE=redis"
      - "REDIS_HOST=proxitok-redis"
      - "REDIS_PORT=6379"
      - "API_SIGNER_URL=http://proxitok-signer:8080/signature"
    volumes:
      - "proxitok-cache:/cache"
    depends_on:
      - proxitok-redis
      - proxitok-signer
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.proxitok.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.proxitok.entrypoints: websecure
      traefik.http.routers.proxitok.service: proxitok
      traefik.http.routers.proxitok.tls.certresolver: myresolver
      traefik.http.services.proxitok.loadbalancer.server.port: 80

  proxitok-redis:
    container_name: proxitok-redis
    image: docker.io/redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    networks:
        - tipi_main_network

  proxitok-signer:
    container_name: proxitok-signer
    image: ghcr.io/pablouser1/signtok:master
    networks:
      - tipi_main_network


volumes:
  proxitok-cache: