version: "3.7"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:22.10.20221021
    container_name: bookstack
    environment:
      - APP_URL=http://${INTERNAL_IP}:${APP_PORT}
      - DB_HOST=bookstack-db
      - DB_USERNAME=tipi
      - DB_PASSWORD=${BOOKSTACK_DB_PASS}
      - DB_DATABASE=bookstackapp
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    dns:
      - ${DNS_IP}
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - bookstack-db
    networks:
      - tipi_main_network

  bookstack-db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack-db
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${BOOKSTACK_DB_PASS}
    volumes:
      - ${APP_DATA_DIR}/data/db:/config
    restart: unless-stopped
    networks:
      - tipi_main_network