version: "3.7"
services:
  moneroblock:
    image: sethsimmons/moneroblock:v0.1.2
    restart: unless-stopped
    container_name: moneroblock
    ports:
      - ${APP_PORT}:31312
    command:
      - "--daemon"
      - "${DAEMON_ADDRESS:-node.sethforprivacy.com:18089}"
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.moneroblock.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.moneroblock.entrypoints: websecure
      traefik.http.routers.moneroblock.service: moneroblock
      traefik.http.routers.moneroblock.tls.certresolver: myresolver
      traefik.http.services.moneroblock.loadbalancer.server.port: 31312
