version: "3"

services:
  mastodon:
    container_name: mastodon
    image: ghcr.io/mastodon/mastodon:v4.1
    command: 'bash -c "bundle exec rails db:migrate; bundle exec rails db:seed; rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"'
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${APP_DATA_DIR}/data/mastodon-public:/mastodon/public
    environment:
      - LOCAL_DOMAIN=${APP_DOMAIN}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - REDIS_HOST=mastodon-redis
      - REDIS_PASSWORD=${MASTODON_REDIS_PASSWORD}
      - REDIS_PORT=6379
      - DB_HOST=mastodon-db
      - DB_USER=tipi
      - DB_NAME=mastodon
      - DB_PASS=${MASTODON_POSTGRES_PASSWORD}
      - DB_PORT=5432
      - ES_ENABLED=false
      - ES_HOST=mastodon-es
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=password
      - SECRET_KEY_BASE=${MASTODON_SECRET_KEY_BASE}
      - OTP_SECRET=${MASTODON_OTP_SECRET}
      - SMTP_SERVER=${MASTODON_SMTP_SERVER}
      - SMTP_PORT=${MASTODON_SMTP_PORT}
      - SMTP_LOGIN=${MASTODON_SMTP_LOGIN}
      - SMTP_PASSWORD=${MASTODON_SMTP_PASSWORD}
      - SMTP_FROM_ADDRESS=${MASTODON_SMTP_FROM_ADDRESS}
      - S3_ENABLED=false
      - S3_BUCKET=files.example.com
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - S3_ALIAS_HOST=files.example.com
      - IP_RETENTION_PERIOD=31556952
      - SESSION_RETENTION_PERIOD=31556952
      - STREAMING_API_BASE_URL=https://${MASTODON_STREAMING_URL}
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.mastodon.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.mastodon.entrypoints: websecure
      traefik.http.routers.mastodon.service: mastodon
      traefik.http.routers.mastodon.tls.certresolver: myresolver
      traefik.http.services.mastodon.loadbalancer.server.port: 3000
    depends_on:
      mastodon-db:
        condition: service_healthy
      mastodon-redis:
        condition: service_healthy
      

  mastodon-db:
    restart: always
    container_name: mastodon-db
    image: postgres:14-alpine
    shm_size: 256mb
    environment:
      POSTGRES_PASSWORD: ${MASTODON_POSTGRES_PASSWORD}
      POSTGRES_USER: tipi
      POSTGRES_DB: mastodon
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHODL: trust
    networks:
      - tipi_main_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data

  mastodon-redis:
    restart: always
    image: redis:7-alpine
    command: redis-server --appendonly yes --replica-read-only no --requirepass "${MASTODON_REDIS_PASSWORD}"
    container_name: mastodon-redis
    networks:
      - tipi_main_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data

  mastodon-streaming:
    container_name:  mastodon-streaming
    image: ghcr.io/mastodon/mastodon:v4.1
    command: 'node ./streaming'
    ports:
      - 8211:4000
    environment:
      - LOCAL_DOMAIN=${APP_DOMAIN}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - REDIS_HOST=mastodon-redis
      - REDIS_PASSWORD=${MASTODON_REDIS_PASSWORD}
      - REDIS_PORT=6379
      - DB_HOST=mastodon-db
      - DB_USER=tipi
      - DB_NAME=mastodon
      - DB_PASS=${MASTODON_POSTGRES_PASSWORD}
      - DB_PORT=5432
      - ES_ENABLED=false
      - ES_HOST=mastodon-es
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=password
      - SECRET_KEY_BASE=${MASTODON_SECRET_KEY_BASE}
      - OTP_SECRET=${MASTODON_OTP_SECRET}
      - SMTP_SERVER=${MASTODON_SMTP_SERVER}
      - SMTP_PORT=${MASTODON_SMTP_PORT}
      - SMTP_LOGIN=${MASTODON_SMTP_LOGIN}
      - SMTP_PASSWORD=${MASTODON_SMTP_PASSWORD}
      - SMTP_FROM_ADDRESS=${MASTODON_SMTP_FROM_ADDRESS}
      - S3_ENABLED=false
      - S3_BUCKET=files.example.com
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - S3_ALIAS_HOST=files.example.com
      - IP_RETENTION_PERIOD=31556952
      - SESSION_RETENTION_PERIOD=31556952
      - STREAMING_API_BASE_URL=https://${MASTODON_STREAMING_URL}
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.mastodon-streaming.rule: Host(`${MASTODON_STREAMING_URL}`)
      traefik.http.routers.mastodon-streaming.entrypoints: websecure
      traefik.http.routers.mastodon-streaming.service: mastodon-streaming
      traefik.http.routers.mastodon-streaming.tls.certresolver: myresolver
      traefik.http.services.mastodon-streaming.loadbalancer.server.port: 4000
    depends_on:
      mastodon-db:
        condition: service_healthy
      mastodon-redis:
        condition: service_healthy

  mastodon-sidekiq:
    container_name: mastodon-sidekiq
    image: ghcr.io/mastodon/mastodon:v4.1
    command: 'bundle exec sidekiq'
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${APP_DATA_DIR}/data/mastodon-public:/mastodon/public
    environment:
      - LOCAL_DOMAIN=${APP_DOMAIN}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - REDIS_HOST=mastodon-redis
      - REDIS_PASSWORD=${MASTODON_REDIS_PASSWORD}
      - REDIS_PORT=6379
      - DB_HOST=mastodon-db
      - DB_USER=tipi
      - DB_NAME=mastodon
      - DB_PASS=${MASTODON_POSTGRES_PASSWORD}
      - DB_PORT=5432
      - ES_ENABLED=false
      - ES_HOST=mastodon-es
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=password
      - SECRET_KEY_BASE=${MASTODON_SECRET_KEY_BASE}
      - OTP_SECRET=${MASTODON_OTP_SECRET}
      - SMTP_SERVER=${MASTODON_SMTP_SERVER}
      - SMTP_PORT=${MASTODON_SMTP_PORT}
      - SMTP_LOGIN=${MASTODON_SMTP_LOGIN}
      - SMTP_PASSWORD=${MASTODON_SMTP_PASSWORD}
      - SMTP_FROM_ADDRESS=${MASTODON_SMTP_FROM_ADDRESS}
      - S3_ENABLED=false
      - S3_BUCKET=files.example.com
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - S3_ALIAS_HOST=files.example.com
      - IP_RETENTION_PERIOD=31556952
      - SESSION_RETENTION_PERIOD=31556952
      - STREAMING_API_BASE_URL=https://${MASTODON_STREAMING_URL}
    restart: unless-stopped
    networks:
      - tipi_main_network
    depends_on:
      mastodon-db:
        condition: service_healthy
      mastodon-redis:
        condition: service_healthy