version: '3.9'

services:
  minio:
    container_name: minio
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=Host(`${APP_DOMAIN}`)
    ports:
      - ${APP_PORT}:9001
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/minio/data:/data
    networks:
      - tipi_main_network
    command: "server --console-address :9001 /data"
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.minio.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.minio.entrypoints: websecure
      traefik.http.routers.minio.service: minio
      traefik.http.routers.minio.tls.certresolver: myresolver
      traefik.http.services.minio.loadbalancer.server.port: 9001
