version: "3.7"

services:
  syncthing:
    container_name: syncthing
    image: syncthing/syncthing:1.23
    stop_grace_period: 1m
    hostname: tipi
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/var/syncthing
    ports:
      - ${APP_PORT}:8384
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.syncthing.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.syncthing.entrypoints: websecure
      traefik.http.routers.syncthing.service: syncthing
      traefik.http.routers.syncthing.tls.certresolver: myresolver
      traefik.http.services.syncthing.loadbalancer.server.port: 8384
