version: "3.9"

services:
  cloudflared:
    image: wisdomsky/cloudflared-web:2023.8.2
    container_name: cloudflared
    restart: unless-stopped
    network_mode: host
    volumes:
     - ${APP_DATA_DIR}/data/cloudflared/config:/config