version: '3.9'
services:
  slskd:
    container_name: slskd
    image: slskd/slskd:0.20.1
    environment:
        - SLSKD_WEB_USER=${SLSKD_WEB_USER}
        - SLSKD_WEB_PASSWORD=${SLSKD_WEB_PASSWORD}
        - SLSKD_USER=${SLSKD_USER}
        - SLSKD_PASSWORD=${SLSKD_PASSWORD}
        - SLSKD_REMOTE_CONFIGURATION=${SLSKD_REMOTE_CONFIGURATION}
        - SLSKD_CONFIG=${APP_DATA_DIR}/data/slskd.yml
        - SLSKD_SHARED_DIR=${ROOT_FOLDER_HOST}/media/downloads/complete
    volumes:
        - ${APP_DATA_DIR}:/app:rw
        - ${ROOT_FOLDER_HOST}/media/downloads:/downloads:rw
    ports:
        - ${APP_PORT}:5031
    restart: unless-stopped
    networks:
        - tipi_main_network
