version: "3.9"
services:
      
  wordpress:
    container_name: wordpress
    image: wordpress:6.4.1
    hostname: changedetection
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: always
    depends_on:
      - mariadb
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress-web-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress-web.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress-web-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-web-insecure.entrypoints: web
        traefik.http.routers.wordpress-web-insecure.service: wordpress-web
        traefik.http.routers.wordpress-web-insecure.middlewares: wordpress-web-redirect
        # Websecure
        traefik.http.routers.wordpress-web.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-web.entrypoints: websecure
        traefik.http.routers.wordpress-web.service: wordpress-web
        traefik.http.routers.wordpress-web.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress-web-local-insecure.rule: Host(`wordpress-web.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-web-local-insecure.entrypoints: web
        traefik.http.routers.wordpress-web-local-insecure.service: wordpress-web
        traefik.http.routers.wordpress-web-local-insecure.middlewares: wordpress-web-redirect
        # Local domain secure
        traefik.http.routers.wordpress-web-local.rule: Host(`wordpress-web.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-web-local.entrypoints: websecure
        traefik.http.routers.wordpress-web-local.service: wordpress-web
        traefik.http.routers.wordpress-web-local.tls: true

  mariadb:
    container_name: mariadb
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: always
    networks:
      - tipi_main_network

  phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin:5.2.1
      environment:
        - PMA_HOST=mariadb
        - PMA_PORT=3306
        - PMA_USER=${DB_USER}
        - PMA_PASSWORD=${DB_PASSWORD}
      restart: always
      networks:
        - tipi_main_network