version: '3.7'
services:
  chatpad:
    image: ghcr.io/deiucanta/chatpad:latest
    container_name: chatpad
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.chatpad.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.chatpad.entrypoints: websecure
      traefik.http.routers.chatpad.service: chatpad
      traefik.http.routers.chatpad.tls.certresolver: myresolver
      traefik.http.services.chatpad.loadbalancer.server.port: 80
